"""Tests for D1 (locate) -- the handedness triple product and the facing instrument.

The properties that matter here are mathematical, and they are what the whole D1 argument
rests on, so they are tested directly rather than through the report: a proper rotation
must leave the handedness sign alone, and a reflection must invert it. If those two ever
stopped holding, every conclusion in `docs/reviews/facing-location-2026-09-02.md` would
be void and nothing else in the repo would notice.

The report-shaped tests skip when the artefacts are absent -- `artifacts/` is gitignored
and regenerated by `tools/compare/facing_location.py`.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys

import numpy as np
import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "compare"))
sys.path.insert(0, str(ROOT / "tools" / "compare" / "extractors"))

from facing_location import (  # noqa: E402
    block_bootstrap_median,
    rig_to_capture,
    triple,
    unit,
)

REPORT = ROOT / "artifacts/compare/facing-location.json"


def _random_bodies(count: int = 64, seed: int = 7) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """A crowd of plausible bodies: across, up and forward roughly orthogonal, jittered."""
    rng = np.random.default_rng(seed)
    across = unit(np.array([1.0, 0.0, 0.0]) + rng.normal(0, 0.15, (count, 3)))
    up = unit(np.array([0.0, 0.0, 1.0]) + rng.normal(0, 0.15, (count, 3)))
    forward = unit(np.cross(up, across))
    return across, up, forward


def test_triple_product_survives_every_proper_rotation() -> None:
    """A yaw is a rotation, and the mirror instrument must be blind to it -- otherwise it
    would flag the 180 degree turn as a mirror and the two failures could not be told
    apart, which is the entire reason this figure exists beside the forward-dot."""
    from scipy.spatial.transform import Rotation

    across, up, forward = _random_bodies()
    before = np.sign(triple(across, up, forward))
    rng = np.random.default_rng(11)
    for _ in range(20):
        rotation = Rotation.from_rotvec(rng.normal(0, 2.0, 3))
        after = np.sign(triple(rotation.apply(across), rotation.apply(up), rotation.apply(forward)))
        assert np.array_equal(before, after)


def test_triple_product_inverts_under_every_reflection() -> None:
    """And a mirror must always flip it -- for any reflection plane, not just the axes."""
    across, up, forward = _random_bodies()
    before = np.sign(triple(across, up, forward))
    rng = np.random.default_rng(13)
    for _ in range(20):
        normal = unit(rng.normal(0, 1.0, 3)[None, :])[0]
        householder = np.eye(3) - 2.0 * np.outer(normal, normal)
        assert np.linalg.det(householder) < 0
        after = np.sign(triple(across @ householder.T, up @ householder.T,
                               forward @ householder.T))
        assert np.array_equal(before, -after)


def test_a_sagittal_mirror_is_invisible_to_a_forward_dot() -> None:
    """The plan's D1 gate card asks for 'a mirrored self-consistent human must fail the
    forward-dot'. It cannot: exchanging left and right leaves facing exactly where it was.
    This test pins that down, because it is the reason the gate needs a second band."""
    across, up, forward = _random_bodies()
    mirrored_across = -across                      # reflect in the (up, forward) plane
    assert np.allclose(np.einsum("fj,fj->f", forward, forward), 1.0)
    assert np.array_equal(np.sign(triple(across, up, forward)),
                          -np.sign(triple(mirrored_across, up, forward)))
    # facing is untouched, so no forward-dot can reject it
    assert np.allclose(np.einsum("fj,fj->f", forward, forward), 1.0)


def test_a_yaw180_is_invisible_to_the_handedness_sign_but_not_to_the_forward_dot() -> None:
    """The dual of the test above, and together they are why both bands ship."""
    across, up, forward = _random_bodies()
    turned_across, turned_forward = -across, -forward       # 180 degrees about `up`
    assert np.array_equal(np.sign(triple(across, up, forward)),
                          np.sign(triple(turned_across, up, turned_forward)))
    assert np.allclose(np.einsum("fj,fj->f", turned_forward, forward), -1.0)


def test_rig_to_capture_inverts_the_pipelines_own_change_of_basis() -> None:
    """`positions_to_body_track` maps the capture's Z-up world into rig space; every figure
    in this instrument depends on undoing exactly that and nothing else."""
    sys.path.insert(0, str(ROOT / "src"))
    from autoanim_gnm.commercial_multiview import DETAILED_HUMANOID  # noqa: F401

    rng = np.random.default_rng(3)
    z_up = rng.normal(0, 1.0, (50, 3))
    to_rig = z_up[..., (0, 2, 1)].copy()
    to_rig[..., 2] *= -1.0
    assert np.allclose(rig_to_capture(to_rig), z_up)


def test_block_bootstrap_reports_a_median_and_an_interval() -> None:
    rng = np.random.default_rng(5)
    values = np.cumsum(rng.normal(0, 0.05, 400)) * 0.0 - 0.9 + rng.normal(0, 0.01, 400)
    out = block_bootstrap_median(values)
    assert out["ci95"][0] <= out["median"] <= out["ci95"][1]
    assert out["block_length"] == 15


def test_the_rest_skeleton_is_no_longer_mirrored_relative_to_its_own_mesh() -> None:
    """The D1 finding, and then its repair, read straight out of code with no artefacts and
    no capture. Until 2026-09-02 the bones named Left sat at -X while the eyes and toes sat
    at +Z; a right-handed body facing +Z with up +Y has its anatomical left at +X, so that
    was a mirror. `docs/reviews/facing-fix-2026-09-02.md` negated the rest X, and this test
    was inverted rather than deleted so the direction of the repair stays on the record."""
    sys.path.insert(0, str(ROOT / "src"))
    from autoanim_gnm.commercial_multiview import DETAILED_HUMANOID

    positions: dict[str, np.ndarray] = {}
    for joint in DETAILED_HUMANOID.joints:
        offset = np.asarray(joint.rest_translation_m, dtype=np.float64)
        positions[joint.name] = offset if joint.parent == -1 else (
            offset + positions[DETAILED_HUMANOID.joints[joint.parent].name])
    assert positions["RightUpperArm"][0] < 0 < positions["LeftUpperArm"][0]
    assert positions["LeftEye"][2] > positions["Head"][2]           # the face is at +Z
    assert positions["LeftToes"][2] > positions["LeftFoot"][2]      # and so are the toes
    across = positions["RightUpperArm"] - positions["LeftUpperArm"]
    up = positions["Neck"] - positions["Hips"]
    forward = positions["LeftToes"] - positions["LeftFoot"]
    # -1, which is what every real human measured in this lane reads. It was +1 before.
    assert np.sign(np.dot(np.cross(across, up), forward)) == -1.0


def test_the_head_solve_no_longer_carries_the_mirror_at_its_own_site() -> None:
    """The mirror's THIRD site, and its repair. The head is not carried by the torso frame
    -- it is set as an absolute world rotation from its own rigid fit -- so mirroring the
    skeleton and the mesh does not reach it. `CANONICAL_HEAD_AXES` used to declare the
    subject's left to be rig -X and forward to be rig -Z, while the asset's nose, eyes and
    toes are all at rig +Z: a perfectly good right-handed frame that was a 180 degree yaw
    of the geometry it drives, which is why the delivered head pointed backwards by its own
    route. Inverted on 2026-09-02 as this docstring instructed, not deleted."""
    sys.path.insert(0, str(ROOT / "src"))
    from autoanim_gnm.head_orientation import CANONICAL_HEAD_AXES

    axes = np.asarray(CANONICAL_HEAD_AXES, dtype=np.float64)
    left, up, forward = axes[:, 0], axes[:, 1], axes[:, 2]
    assert np.allclose(np.cross(left, up), forward), "the frame is at least self-consistent"

    def to_rig(v: np.ndarray) -> np.ndarray:      # capture (Z up) -> rig (Y up)
        return np.array([v[0], v[2], -v[1]])

    # ...and the asset it drives puts the face at rig +Z, which it now agrees with.
    assert np.allclose(to_rig(forward), [0.0, 0.0, 1.0])
    assert not np.allclose(to_rig(forward), [0.0, 0.0, -1.0])


def test_camera_overlay_sets_the_scene_fps_before_it_imports() -> None:
    """The 2026-09-02 repair. Order is the whole fix: setting fps after the import does
    nothing, because the importer has already converted the keyframe times."""
    source = (ROOT / "tools/swap-harness/camera_overlay.py").read_text()
    assert source.index("render.fps") < source.index("import_scene.gltf")
    assert "sample_rate_hz" in source
    assert "POSE CHECK" in source


@pytest.mark.skipif(not REPORT.exists(), reason="run tools/compare/facing_location.py first")
class TestReport:
    @staticmethod
    def _report() -> dict:
        return json.loads(REPORT.read_text())

    def test_the_delivered_rig_agrees_with_itself_about_forward(self) -> None:
        """The location, as one bit: BEFORE the 2026-09-02 fix the same rig read through its
        feet and through its torso gave opposite handedness (`capture == mamma == feet ==
        -torso`), which no proper rotation can do -- the torso carried the rest's mirror
        through as a yaw and the independently-solved feet did not. Since the relabel
        shipped, all four read the same sign. A recurrence of the mirror flips `torso`."""
        arms = self._report()["triple_product"]["arms"]
        for subject in ("subject_00", "subject_01"):
            feet = arms["delivered_rig_forward_from_its_FEET"][subject]["sign_median"]
            torso = arms["delivered_rig_forward_from_its_TORSO"][subject]["sign_median"]
            capture = arms["our_triangulated_capture"][subject]["sign_median"]
            mamma = arms["mamma_pred_joints"][subject]["sign_median"]
            assert capture == mamma == feet == torso  # was `== -torso` until the fix

    def test_the_delivered_surface_faces_forward(self) -> None:
        """Measured on the shipped GLB with no joint name involved -- the reading I6's
        whole-body control could not give. Until 2026-09-02 the nose's CI sat below -0.5
        and the pelvis below -0.9 (the mirror); since the fix every part points with the
        performer. The feet were right both before and after, being solved from the toes."""
        dots = self._report()["forward_dot"]
        for subject in ("subject_00", "subject_01"):
            assert dots[subject]["delivered_MESH_nose"]["vs_our_capture_forward"]["ci95"][0] > 0.5   # was ci95[1] < -0.5
            assert dots[subject]["delivered_torso_Hips"]["vs_our_capture_forward"]["median"] > 0.9  # was < -0.9
            # and the feet, solved separately, are right
            assert dots[subject]["delivered_feet"]["vs_our_capture_forward"]["median"] > 0.5

    def test_the_oracle_says_the_two_references_agree_about_facing(self) -> None:
        """A gate needs an oracle arm. If our capture and MAMMA disagreed about which way
        the performers face, none of the figures above would mean anything."""
        dots = self._report()["forward_dot"]
        for subject in ("subject_00", "subject_01"):
            oracle = dots[subject]["ORACLE_mamma_forward_vs_our_capture_forward"]
            assert oracle["vs_our_capture_forward"]["ci95"][0] > 0.95

    def test_the_extractor_returns_the_x_star_shape(self) -> None:
        from d1_facing import x_facing

        figures, controls = x_facing({})
        assert figures and controls
        for entry in figures + controls:
            assert set(entry) >= {"key", "label", "value", "unit", "reference", "better"}
            assert entry["value"] is None or -1.0001 <= float(entry["value"]) <= 1.0001
        keys = [e["key"] for e in figures + controls]
        assert len(keys) == len(set(keys)), "duplicate figure keys collide in the registry"
